---
####################################################################
# Install/Setup node exporter
####################################################################
- name: Create node exporter Group
  ansible.builtin.group:
    name: nodeexporter
    state: present

- name: Create node exporter User
  ansible.builtin.user:
    name: nodeexporter
    shell: /usr/sbin/nologin
    state: present

- name: Stat node exporter
  ansible.builtin.stat:
    path: "/usr/local/bin/node_exporter"
  register: node_exporter_install

- name: Download node exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_dl_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: 0644
  when: not node_exporter_install.stat.exists

- name: Extract node exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: not node_exporter_install.stat.exists

- name: Move node exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  when: not node_exporter_install.stat.exists

- name: Copy node exporter service
  ansible.builtin.template:
    src: "templates/node_exporter.service.j2"
    dest: "/etc/systemd/system/node-exporter.service"
    owner: "root"
    group: "root"
    mode: 0600

- name: Start node exporter service
  ansible.builtin.service:
    name: "node-exporter"
    enabled: yes
    state: restarted

- name: Allow node exporter (9000/TCP)
  community.general.ufw:
    rule: allow
    port: "{{ node_exporter_port }}"
    proto: tcp

####################################################################
# Healthcheck Node Exporter
####################################################################
- name: Node Exporter health check
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ node_exporter_port }}/metrics"
    follow_redirects: none
    method: GET
    status_code: 200
  register: node_exporter_result
  until: node_exporter_result.status == 200
  retries: 720  # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5  # Every 5 seconds
