---
####################################################################
# Change default hostname
####################################################################
- name: Change the hostname to match with the inventory configuration
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_state

- name: Reboot after changing the hostname  # noqa no-handler
  ansible.windows.win_reboot:
  when: hostname_state is changed

####################################################################
# Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  community.windows.win_timezone:
    timezone: '{{ timezone.split("/")[1] }}'
  tags: 'sysprep'

####################################################################
# DISABLE updates
####################################################################
- name: Disable Windows update service
  ansible.windows.win_service:
    name: 'wuauserv'
    state: 'stopped'
    start_mode: 'disabled'

####################################################################
# Enable Prefetch and Superfetch
####################################################################
- name: Enable Windows Prefetch
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters
    name: EnablePrefetcher
    data: 3
    type: dword

- name: Enable Windows Superfetch
  ansible.windows.win_command: sc config "SysMain" start=auto

- name: Start Windows Superfetch
  ansible.windows.win_command: sc start "SysMain"

####################################################################
# Install software
####################################################################
- name: Stat Firefox
  ansible.windows.win_stat:
    path: 'C:\Program Files\Mozilla Firefox\firefox.exe'
  register: win_firefox

- name: Install Firefox
  ansible.windows.win_package:
    path: "{{ firefox_dl_url }}"
    state: present
  when: not win_firefox.stat.exists

####################################################################
# Delay WinRM for reliability
####################################################################
- name: Ensure WinRM starts after the system has finished booting up
  ansible.windows.win_service:
    name: WinRM
    start_mode: delayed
