---
####################################### General #######################################
internal_domain: magnumtempus.financial
external_domain: magnumtempusfinancial.com
company_name: 'Magnum Tempus Financial'
timezone: 'Etc/UTC'
