---
# WinRM
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore
ansible_user: Administrator
ansible_password: "{{ lookup('amazon.aws.aws_secret', 'DEFCON_2023_OBSIDIAN_win_domain_admin_passwd') }}"
