---
####################################################################
# Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  win_timezone:
    timezone: '{{ timezone.split("/")[1] }}'
  tags: 'sysprep'

####################################################################
# DISABLE updates
####################################################################
- name: Disable Windows update service
  win_service:
    name: 'wuauserv'
    state: 'stopped'
    start_mode: 'disabled'

####################################################################
# Enable Prefetch and Superfetch
####################################################################
- name: Enable Windows Prefetch
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters
    name: EnablePrefetcher
    data: 3
    type: dword

- name: Start Windows Superfetch
  ansible.windows.win_service:
    name: SysMain
    state: started
    start_mode: auto

####################################################################
# Install software
####################################################################
- name: Install chocolatey
  win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
    state: present

- name: Install software
  win_chocolatey:
    name: '{{ item }}'
    state: latest
  with_items:
    - 'googlechrome'
    - 'vscode'
    - 'wireshark'
    - 'sysinternals'

####################################################################
# Delay WinRM for reliability
####################################################################
- name: Ensure WinRM starts after the system has finished booting up
  win_service:
    name: WinRM
    start_mode: delayed
