---

# TODO: add btv one
# cribl_license_dat: cribl-license.dat
cribl_api_password: "{{ lookup('amazon.aws.aws_secret', 'DEFCON_2023_OBSIDIAN-cribl-api-pass', region=aws_region) }}"

cribl_fqdn: "cribl.{{ external_domain }}"

cribl_in_elastic_version: 8.7.0

cribl_inputs_template: conf/cribl/inputs.yml
cribl_outputs_template: conf/cribl/outputs.yml

cribl_elastic_in_tls: true
cribl_elastic_in_cert_name: magnumtempusfinancial

# juju4.harden_nginx
hardenwebserver_disable_http: true
hardenwebserver_cert: certbot
certbot_args: "--register-unsafely-without-email --agree-tos --domains {{ cribl_fqdn }}"
hardenwebserver_https_template: conf/cribl/cribl-nginx.conf.j2
# https://cribl.magnumtempusfinancial.com
# hardenwebserver_header_csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'report-sample'; connect-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:;base-uri 'none'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; report-uri /csp/report.php;"
hardenwebserver_header_csp: "upgrade-insecure-requests; report-uri /csp/report.php;"
hardenwebserver_ssl_cert: "/etc/letsencrypt/live/{{ cribl_fqdn }}/fullchain.pem"
hardenwebserver_ssl_key: "/etc/letsencrypt/live/{{ cribl_fqdn }}/privkey.pem"
hardenwebserver_systemd_dir_acl:
  - { p: /etc/letsencrypt/archive, perm: rx, m: '0711' }
  - { p: /etc/letsencrypt/live, perm: rx, m: '0711' }
  - { p: "/etc/ssl/private", perm: rx, m: '0710' }
  - { p: "/var/log/nginx", perm: rwx, m: '0755' }
hardenwebserver_systemd_files_acl:
  - { p: "/etc/letsencrypt/live/{{ cribl_fqdn }}/privkey.pem", perm: r }
  - { p: "/etc/ssl/private/dhparam4.pem", perm: r }
