####################################################################
# Install and configure Uncomplicated Firewall (ufw)
####################################################################
- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP
  ufw:
    rule: allow
    name: "NGINX http"

- name: Allow HTTPS (443/TCP)
  ufw:
    rule: allow
    name: "NGINX https"

- name: Allow ingest traffic to Logstash
  ufw:
    rule: allow
    port: "5044"
    proto: "tcp"

- name: Enable UFW
  ufw:
    state: enabled
