---

filebeat_inputs:
  - type: log
    paths:
      - "/var/log/*.log"
  - type: log
    paths:
      - "/var/log/syslog"
  - type: log
    paths:
      - "/var/log/osquery/osqueryd.*.log"
  - type: log
    paths:
      - "/var/log/sysmon/sysmon.log"
  # https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-journald.html
  - type: journald
    id: everything
  # nginx as it seems module is not working
  - type: log
    paths:
      - "/var/log/nginx/access.log"
  - type: log
    paths:
      - "/var/log/nginx/error.log"
