---
####################################################################
# Change default hostname
####################################################################
- name: Change the hostname to match with the inventory configuration
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - Reboot Windows

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

####################################################################
# Configure DNS settings for clients
####################################################################
- name: Set DNS address to Domain Controller
  ansible.windows.win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
      - "{{ groups.win_domain_controller[0] }}"
  register: dns_state

####################################################################
# Join computer to domain
####################################################################
- name: Join Windows domain
  # https://docs.ansible.com/ansible/2.9/modules/win_domain_membership_module.html
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ internal_domain }}"
    domain_admin_user: "Administrator@{{ internal_domain }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  notify:
    - Reboot Windows

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
