---
####################################################################
# Configure software specifically for clients
####################################################################
- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey

- name: Install software
  chocolatey.chocolatey.win_chocolatey:
    name:
      - 'googlechrome'
      - 'vscode'
      - 'wireshark'
      - 'sysinternals'
    state: latest
