---
# tasks file for ansible/roles/windows_clients

- name: Add Windows client to domain
  ansible.builtin.import_tasks: add_client_to_domain.yml
- name: Install choclately and tools
  ansible.builtin.import_tasks: install_software.yml
