####################################################################
# Install/Setup Java JDK
####################################################################
- name: Install Java JDK
  ansible.builtin.apt:
    deb: "{{ java_dl_url }}"
