---
# tasks file for ansible/log4j

- name: Init setup
  ansible.builtin.import_tasks: init.yml
- name: Install Java JDK
  ansible.builtin.import_tasks: install_java.yml
- name: Install/Setup vulnerable Log4j webserver
  ansible.builtin.import_tasks: setup_log4j_web_server.yml
- name: Install NGINX
  ansible.builtin.import_tasks: setup_nginx.yml
