####################################################################
# Change default hostname to DC
####################################################################
- name: Change the hostname to DC for domain controller
  win_hostname:
    name: "dc"
  register: hostname_state

- name: Reboot after changing the hostname
  win_reboot:
  when: hostname_state is changed

####################################################################
# Create domain and reboot
####################################################################
- name: Create new Windows domain in a new forest
  # https://docs.ansible.com/ansible/2.9/modules/win_domain_module.html
  win_domain:
    dns_domain_name: "{{ internal_domain }}"
    safe_mode_password: "{{ safe_mode_password }}"
  register: domain_install

- name: Reboot after installing Windows domain if required
  win_reboot:
  when: domain_install.reboot_required

####################################################################
# Promote server to DC
####################################################################
- name: Ensure a server is a domain controller
  # https://docs.ansible.com/ansible/2.9/modules/win_domain_controller_module.html
  win_domain_controller:
    dns_domain_name: "{{ internal_domain }}"
    domain_admin_user: "Administrator@{{ internal_domain }}"
    domain_admin_password: "{{ ansible_password }}"
    safe_mode_password: "{{ safe_mode_password }}"
    state: domain_controller
  register: domain_controller_install

- name: Reboot after promoting a Domain Controller server if required
  win_reboot:
  when: domain_controller_install.reboot_required
