---

- name: Add Secrets in AWS Secrets Manager
  hosts: localhost
  # connection: local
  vars:
    aws_region: us-east-2
    secrets_list:
      - {secret_name: "DEFCON_2023_OBSIDIAN-cribl-admin-pass",
         secret_string: "[REDACTED]"
      }
      - {secret_name: "DEFCON_2023_OBSIDIAN-securityonion-admin-pass",
         secret_string: "[REDACTED]"
      }
      - {secret_name: "DEFCON_2023_OBSIDIAN-securityonion-soremote-pass",
         secret_string: "[REDACTED]"
      }
      - {secret_name: "DEFCON_2023_OBSIDIAN-securityonion-webuser-pass",
         secret_string: "[REDACTED]"
      }
      - {secret_name: "DEFCON_2023_OBSIDIAN-breakglass-pass",
         secret_string: "[REDACTED]"
      }
  tasks:
    - name: Add string to AWS Secrets Manager
      community.aws.secretsmanager_secret:
        name: "{{ item.secret_name }}"
        state: present
        secret_type: 'string'
        secret: "{{ item.secret_string }}"
        region: "{{ aws_region }}"
        tags:
          Project: DEFCON_2023_OBSIDIAN
      loop: "{{ secrets_list2 }}"
