---

- name: Test/List AWS resources
  hosts: localhost
  vars:
    aws_region: us-east-2
  tasks:
    - name: Gather information about all EC2 instances
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Project": DEFCON_2023_OBSIDIAN
      register: ec2_info
    - name: Debug | EC2 instances info
      ansible.builtin.debug:
        var: ec2_info
        verbosity: 1
    - name: Gather information about all S3 buckets
      community.aws.s3_bucket_info:
      register: s3_info
    - name: Debug | S3 instancess info
      ansible.builtin.debug:
        var: s3_info
        verbosity: 1
    - name: Retrieve a list of objects in S3 bucket
      amazon.aws.s3_object_info:
        bucket_name: defcon-2023-obsidian-teleport-kxl6y
      register: s3_info1
      when: false
    - name: Debug | S3 info
      ansible.builtin.debug:
        var: s3_info1
        verbosity: 1
      when: false
