---
- hosts: 'hmail'
  roles:
    - win_node_exporter
    - prymalinstynct.velociraptor
  tasks:
    - import_tasks: 'roles/windows/init_windows.yml'
    - import_tasks: 'roles/windows/setup_sysmon.yml'
    - import_tasks: 'roles/windows/setup_winlogbeat.yml'
