- hosts: 'win_domain_controller'
  tasks:
    - include_vars: 'group_vars/metrics.yml'
    - include_vars: 'group_vars/velociraptor.yml'
    - import_tasks: 'roles/windows/init_windows.yml'
    - import_tasks: 'roles/windows/domain_controller/setup_domain_controller.yml'
    - import_tasks: 'roles/windows/domain_controller/create_dns_zone.yml'
    - import_tasks: 'roles/windows/domain_controller/create_domain_users.yml'
    - import_tasks: 'roles/windows/domain_controller/create_domain_honeypot_user.yml'
    - import_tasks: 'roles/windows/setup_rdp_servers.yml'
    - import_tasks: 'roles/windows/setup_sysmon.yml'
    - import_tasks: 'roles/windows/setup_winlogbeat.yml'
    - import_tasks: 'roles/windows/setup_velociraptor_win_client.yml'
    - import_tasks: 'roles/windows/setup_node_exporter.yml'
