---

- name: Setup cribl server
  hosts: cribl_server
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - juju4.cribl
    - juju4.harden_nginx
    - node_exporter
  tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
