---

- name: Deploy elastic server
  hosts: elastic
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
  roles:
    - geerlingguy.filebeat
    - juju4.osquery
    - juju4.sysmon
    - node_exporter
    # - prymalinstynct.velociraptor
    - mdsketch.teleport
  tasks:
    - include_vars: 'group_vars/elastic.yml'
    - include_vars: 'group_vars/elastic_secrets.yml'
    - import_tasks: 'roles/linux/elastic/setup_ufw.yml'
    - import_tasks: 'roles/linux/elastic/setup_elasticsearch.yml'
    - import_tasks: 'roles/linux/elastic/setup_kibana.yml'
    # - import_tasks: 'roles/linux/elastic/setup_logstash.yml'
    - import_tasks: 'roles/linux/elastic/setup_nginx.yml'
    - import_tasks: 'roles/linux/elastic/setup_elastic_exporter.yml'
