---
- hosts: 'win_jumpbox'
  roles:
    - win_node_exporter
  tasks:
    - include_vars: 'group_vars/iot.yml'
    - import_tasks: 'roles/windows/init_windows.yml'
    - import_tasks: 'roles/windows/setup_iot_jumpbox.yml'
    - import_tasks: 'roles/windows/setup_rdp_servers.yml'
    - import_tasks: 'roles/windows/setup_sysmon.yml'
    - import_tasks: 'roles/windows/setup_winlogbeat.yml'
