---

- name: Setup splunk server
  hosts: splunk
  become: yes
  become_user: root
  pre_tasks:
    - name: Create splunk group
      ansible.builtin.group:
        name: "{{ splunk.group }}"
    - name: Create splunk user
      ansible.builtin.user:
        name: "{{ splunk.user }}"
        home: "{{ splunk.home }}"
        group: "{{ splunk.group }}"
        groups:
          # to allow splunk to read journald
          - systemd-journal
        append: yes
        system: yes
        comment: splunk user
    - name: Push installer archive from orchestrator
      ansible.builtin.copy:
        src: "{{ splunk_installer_orchestrator_path }}"
        dest: "{{ splunk.build_location }}"
        mode: 0644
    - name: Ensure acl package is present for unprivileged become
      ansible.builtin.package:
        name: acl
        state: present
  roles:
    - splunk_standalone
    - juju4.harden_nginx
    - node_exporter
  handlers:
    - name: Restart Splunkd
      ansible.builtin.service:
        name: Splunkd
        state: restarted
  tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
    - name: Set multiple Splunk indexes
      ansible.builtin.template:
        src: splunk-indexes.conf.j2
        dest: /opt/splunk/etc/apps/search/local/indexes.conf
        mode: 0600
        owner: splunk
        group: splunk
      notify:
        - Restart Splunkd
    - name: Set multiple Splunk HEC inputs attached to separate index
      ansible.builtin.template:
        src: splunk-inputs.conf.j2
        dest: /opt/splunk/etc/apps/search/local/inputs.conf
        mode: 0600
        owner: splunk
        group: splunk
      notify:
        - Restart Splunkd
