---

- name: Setup IoT PLC environment
  hosts: iot_plc
  become: yes
  become_user: root
  pre_tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
    - name: Remove sysmon
      ansible.builtin.package:
        name:
          - sysmonforlinux
          - sysinternalsebpf
        state: absent
      when: false
  roles:
    - davidmarkallison.openplc
    - geerlingguy.filebeat
    - juju4.osquery
    - node_exporter
    - juju4.sysmon
    - prymalinstynct.velociraptor
  tasks:
    # https://github.com/blueteamvillage/DC31-obsidian-sec-eng/issues/104
    - name: Make openplc listen on default interface
      ansible.builtin.replace:
        dest: /opt/OpenPLC_v3/webserver/webserver.py
        regexp: "^            app.run(debug=False, host='.*', threaded=True, port=8080)"
        # https://medium.com/opsops/ansible-default-ipv4-is-not-what-you-think-edb8ab154b10
        replace: "            app.run(debug=False, host='{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}', threaded=True, port=8080)"
        mode: 0644
        backup: true
