---
- hosts: 'win_clients'
  roles:
    - win_node_exporter
    - windows_clients
  tasks:
    - import_tasks: 'roles/windows/setup_sysmon.yml'
    - import_tasks: 'roles/windows/setup_winlogbeat.yml'
