---
- name: Install/Setup Vulnerable Log4j webserver
  become: true
  hosts: log4j
  roles:
    - role: log4j
    - juju4.osquery
    - juju4.sysmon
    - node_exporter
    - prymalinstynct.velociraptor
    - geerlingguy.filebeat
  handlers:
    - name: Restart filebeat
      ansible.builtin.service:
        name: filebeat
        state: restarted
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    # https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html
    # https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-nginx.html
    # better to use a template. keeping this if other things done by command
    # module setup not working, switching to usual file log collection
    - name: Configure nginx module for filebeat
      ansible.builtin.command:
        cmd: filebeat modules enable nginx
      args:
        creates: /etc/filebeat/modules.d/nginx.yml
      when: false
    - name: Configure nginx module for filebeat (2)
      ansible.builtin.template:
        src: filebeat-nginx.yml.j2
        dest: /etc/filebeat/modules.d/nginx.yml
        mode: '0644'
      notify:
        - Restart filebeat
      when: false
    - name: Json logs for nginx
      ansible.builtin.template:
        src: nginx-json-logs.conf.j2
        dest: /etc/nginx/conf.d/json-logs.conf
        mode: '0644'
      notify:
        - Restart nginx
