---

- name: Setup IoT PLC environment
  hosts: iot_plc
  become: yes
  become_user: root
  pre_tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
    - name: Remove sysmon
      ansible.builtin.package:
        name:
          - sysmonforlinux
          - sysinternalsebpf
        state: absent
      when: false
  roles:
    - davidmarkallison.openplc
    - juju4.sysmon
    - geerlingguy.filebeat
    - juju4.osquery
    - node_exporter
    - prymalinstynct.velociraptor
  tasks:
    - import_tasks: "roles/iot_plc/setup_openplc.yml"
    - import_tasks: "roles/iot_plc/setup_ssh.yml"
