---

- name: Setup IoT PLC environment
  hosts: iot_plc
  become: yes
  become_user: root
  pre_tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
    - name: Remove sysmon
      ansible.builtin.package:
        name:
          - sysmonforlinux
          - sysinternalsebpf
        state: absent
      when: false
  roles:
    - davidmarkallison.openplc
    - geerlingguy.filebeat
    - juju4.osquery
    - node_exporter
    - juju4.sysmon
    # - prymalinstynct.velociraptor
