---

- name: Setup IoT environment
  hosts: iot_plc
  become: yes
  become_user: root
  roles:
    - davidmarkallison.openplc
    - geerlingguy.filebeat
    - juju4.osquery
    - juju4.sysmon
    - node_exporter
    - prymalinstynct.velociraptor
  tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
