---

- name: Install Security Onion
  hosts: security_onion
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
  roles:
    # - geerlingguy.docker
    - mdsketch.teleport
    - node_exporter
  handlers:
    - name: Restart so-nginx
      ansible.builtin.command: so-nginx-restart
    - name: Call salt state.highstate
      ansible.builtin.command: salt-call state.highstate
      register: highstate
      until: highstate is success
      # this seems to take a while
      retries: 3
      delay: 180
  tasks:
    - import_tasks: 'roles/linux/install_security_onion.yml'
    - import_tasks: 'roles/linux/setup_nginx_security_onion.yml'
    - import_tasks: 'roles/linux/install_security_onion_sensoroni_workaround.yml'
