---

- name: Setup Corp Docker server
  hosts: docker_server
  become: yes
  become_user: root
  roles:
    - geerlingguy.docker
    - geerlingguy.filebeat
  tasks:
    - import_tasks: 'roles/linux/init_linux.yml'
