---

collections:
  - name: amazon.aws
  - name: splunk-ansible
    src: https://github.com/splunk/splunk-ansible.git
    version: master

roles:
  - name: blueteamvillage.btv-sec-eng-teleport-cluster
    src: https://github.com/blueteamvillage/btv-sec-eng-teleport-cluster
    version: "1.0.0"
