---

- name: Add breakglass user for emergency/serial console
  ansible.builtin.user:
    name: "{{ breakglass_serialuser_user }}"
    password: "{{ breakglass_serialuser_password }}"
    home: /var/_breakglass
    system: true
    groups: admin

####################################################################
# Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  community.general.timezone:
    name: '{{ timezone }}'

####################################################################
# Apt update
####################################################################
- name: Debian | Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

####################################################################
# Reboot
####################################################################
- name: Debian | Check if a reboot is required
  register: file
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: file.stat.exists is defined and file.stat.exists

####################################################################
# Install software
####################################################################
- name: Install softwares
  ansible.builtin.package:
    name:
      - apt-transport-https
      - htop
      - tcpdump
      - net-tools
      - wget
    state: latest
