name: Test PR by running pre-commit

on: [push, pull_request]

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      ########################### Terraform ###########################
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
