name: Test PR by running pre-commit

on: [push, pull_request]

env:
  TERRAFORM_VERSION: 1.3.7

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      ########################### Terraform ###########################
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: Terraform fmt
        id: fmt
        run: cd terraform/ && terraform fmt -check

      - name: Terraform Init
        id: init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        id: validate
        run: cd terraform/ && terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: cd terraform/ && terraform plan -no-color
