name: Test PR

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.10"
  TERRAFORM_VERSION: "1.3.7"
  AWS_ACCOUNT_ID: "106453756913"

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # This is required for actions/checkout@v2

jobs:
  terraform_test:
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions"

      ########################### Terraform ###########################
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: Write SSH public key to disk
        run: echo ${{ secrets.SSH_PUB_KEY }} > terraform/ssh_keys/id_ed25519.pub

      - name: Terraform fmt
        id: fmt
        run: cd terraform/ && terraform fmt -check

      - name: Terraform Init
        id: init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        id: validate
        run: cd terraform/ && terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: cd terraform/ && terraform plan -lock=false

  precommit_test:
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      ########################### python ###########################
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: 'pip'

      - name: Install Python deps
        run: pip install -r ci/requirements.txt

      ########################### pre-commit ###########################
      - name: pre-commit modules
        run: pre-commit run --all-files
