name: Test PR by running pre-commit

on: [push, pull_request]

env:
  TERRAFORM_VERSION: 1.3.7
  AWS_ACCOUNT_ID: 106453756913

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # This is required for actions/checkout@v2

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions"

      ########################### Terraform ###########################
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: Terraform fmt
        id: fmt
        run: cd terraform/ && terraform fmt -check

      - name: Terraform Init
        id: init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        id: validate
        run: cd terraform/ && terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: cd terraform/ && terraform plan -no-color
